import js from '@eslint/js';
import globals from 'globals';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import svelte from 'eslint-plugin-svelte';
import prettier from 'eslint-config-prettier';
import svelteConfig from './svelte.config.js';

export default [
  {
    ignores: [
      'node_modules/',
      'build/',
      '.svelte-kit/',
      '.vercel/',
      'static/',
      'test-results/',
      'playwright-report/',
      'vectorstore.db/',
      // wasm-pack output: generated bindings, regenerated by `npm run wasm`.
      'HCM-middleware/pkg/',
      'HCM-middleware/target/',
    ],
  },

  js.configs.recommended,
  ...tsPlugin.configs['flat/recommended'],
  ...svelte.configs['flat/recommended'],

  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node },
    },
  },

  {
    files: ['**/*.svelte', '**/*.svelte.js', '**/*.svelte.ts'],
    languageOptions: {
      parserOptions: {
        // Svelte 5 components carry TypeScript in `<script lang="ts">`; the svelte parser needs the TS parser for those blocks, and svelte.config.js so it resolves the same preprocessor chain the build uses.
        parser: tsParser,
        svelteConfig,
      },
    },
  },

  {
    files: ['**/*.cjs'],
    languageOptions: { sourceType: 'commonjs' },
    rules: {
      // postcss.config.cjs and tailwind.config.cjs are CommonJS on purpose, because PostCSS loads them synchronously. require() is the correct call there.
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  // Rules switched off because they fight patterns this repo uses deliberately.
  {
    rules: {
      // The wasm bindings are untyped at the boundary, so `any` is how engine results enter the app. Typing them would mean hand-maintaining a second copy of the middleware's shape.
      '@typescript-eslint/no-explicit-any': 'off',
      // Unused function arguments are load-bearing documentation in the diagram and event-handler signatures; only flag unused locals, and let a leading underscore opt out entirely.
      '@typescript-eslint/no-unused-vars': ['error', { args: 'none', varsIgnorePattern: '^_', caughtErrors: 'none' }],
      // 304 hits, essentially all of them in the SVG diagrams, where every {#each} walks a freshly derived array of geometry with no component state or transition attached to a row. Keys would be index-derived noise. Turn this back on if an {#each} ever wraps an input or a stateful child.
      'svelte/require-each-key': 'off',
      // The flagged Maps are imperative pointer bookkeeping inside the drag handlers, never read from markup, so SvelteMap would buy reactivity nothing consumes. The rule cannot tell that case from reactive state.
      'svelte/prefer-svelte-reactivity': 'off',
      // Every hit is a `<!-- svelte-ignore a11y_* -->` aimed at the Svelte compiler, which does still warn there. The rule only sees eslint-plugin-svelte's own a11y rules, and those are off, so it calls live comments unused. Revisit if this config ever enables svelte/a11y-*.
      'svelte/no-unused-svelte-ignore': 'off',
    },
  },

  // Must stay last: turns off the stylistic rules Prettier already owns.
  prettier,
  ...svelte.configs['flat/prettier'],
];
