/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_wasmsubsegment_free(a: number): void;
export function wasmsubsegment_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): number;
export function wasmsubsegment_to_js_value(a: number): number;
export function wasmsubsegment_get_length(a: number): number;
export function wasmsubsegment_get_avg_speed(a: number): number;
export function wasmsubsegment_get_hor_class(a: number): number;
export function __wbg_wasmsegment_free(a: number): void;
export function wasmsegment_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number, e1: number, f1: number, g1: number, h1: number, i1: number): number;
export function wasmsegment_to_js_value(a: number): number;
export function wasmsegment_get_passing_type(a: number): number;
export function wasmsegment_get_length(a: number): number;
export function wasmsegment_get_grade(a: number): number;
export function wasmsegment_get_spl(a: number): number;
export function wasmsegment_get_is_hc(a: number): number;
export function wasmsegment_get_volume(a: number): number;
export function wasmsegment_get_volume_op(a: number): number;
export function wasmsegment_get_flow_rate(a: number): number;
export function wasmsegment_get_flow_rate_o(a: number): number;
export function wasmsegment_get_capacity(a: number): number;
export function wasmsegment_get_ffs(a: number): number;
export function wasmsegment_get_avg_speed(a: number): number;
export function wasmsegment_get_subsegments(a: number): number;
export function wasmsegment_get_vertical_class(a: number): number;
export function wasmsegment_get_phf(a: number): number;
export function wasmsegment_get_phv(a: number): number;
export function wasmsegment_get_percent_followers(a: number): number;
export function wasmsegment_get_followers_density(a: number): number;
export function wasmsegment_get_followers_density_mid(a: number): number;
export function wasmsegment_get_hor_class(a: number): number;
export function __wbg_wasmtwolanehighways_free(a: number): void;
export function wasmtwolanehighways_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): number;
export function wasmtwolanehighways_get_segments(a: number): number;
export function wasmtwolanehighways_identify_vertical_class(a: number, b: number, c: number): void;
export function wasmtwolanehighways_determine_demand_flow(a: number, b: number, c: number): void;
export function wasmtwolanehighways_determine_vertical_alignment(a: number, b: number): number;
export function wasmtwolanehighways_determine_free_flow_speed(a: number, b: number): number;
export function wasmtwolanehighways_estimate_average_speed(a: number, b: number, c: number): void;
export function wasmtwolanehighways_estimate_percent_followers(a: number, b: number): number;
export function wasmtwolanehighways_estimate_average_speed_sf(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function wasmtwolanehighways_estimate_percent_followers_sf(a: number, b: number, c: number, d: number): number;
export function wasmtwolanehighways_determine_follower_density_pl(a: number, b: number, c: number): void;
export function wasmtwolanehighways_determine_follower_density_pc_pz(a: number, b: number): number;
export function wasmtwolanehighways_determine_adjustment_to_follower_density(a: number, b: number): number;
export function wasmtwolanehighways_determine_segment_los(a: number, b: number, c: number, d: number): number;
export function wasmtwolanehighways_determine_facility_los(a: number, b: number, c: number): number;
export function wasmsubsegment_get_design_rad(a: number): number;
export function wasmsubsegment_get_central_angle(a: number): number;
export function wasmsubsegment_get_sup_ele(a: number): number;
export function wasmsegment_subsegs_to_js_value(a: number): number;
export function wasmtwolanehighways_segs_to_js_value(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
