/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_wasmtwsc_free(a: number): void;
export function wasmtwsc_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number, e1: number, f1: number, g1: number, h1: number, i1: number, j1: number, k1: number, l1: number, m1: number, n1: number, o1: number, p1: number, q1: number, r1: number, s1: number, t1: number, u1: number, v1: number, w1: number, x1: number, y1: number, z1: number, a2: number, b2: number, c2: number, d2: number, e2: number, f2: number, g2: number, h2: number, i2: number, j2: number, k2: number, l2: number, m2: number, n2: number, o2: number, p2: number, q2: number, r2: number): void;
export function wasmtwsc_analyze(a: number): void;
export function wasmtwsc_get_flow_rate(a: number, b: number, c: number, d: number): void;
export function wasmtwsc_get_conflicting_flow(a: number, b: number, c: number, d: number): void;
export function wasmtwsc_get_potential_capacity(a: number, b: number, c: number, d: number): void;
export function wasmtwsc_get_movement_capacity(a: number, b: number, c: number, d: number): void;
export function wasmtwsc_get_movement_delay(a: number, b: number, c: number, d: number): void;
export function wasmtwsc_get_movement_los(a: number, b: number, c: number, d: number): void;
export function wasmtwsc_get_movement_queue_95(a: number, b: number, c: number, d: number): void;
export function wasmtwsc_get_lane_count(a: number, b: number, c: number, d: number): void;
export function wasmtwsc_lane_result_to_js_value(a: number, b: number, c: number, d: number, e: number): void;
export function wasmtwsc_get_approach_delays(a: number, b: number): void;
export function wasmtwsc_get_intersection_delay(a: number, b: number): void;
export function wasmtwsc_results_to_js_value(a: number): number;
export function __wbg_wasmfacilitysegment_free(a: number): void;
export function wasmfacilitysegment_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number, e1: number, f1: number): number;
export function wasmfacilitysegment_get_seg_type(a: number, b: number): void;
export function wasmfacilitysegment_get_length_ft(a: number): number;
export function wasmfacilitysegment_get_lanes(a: number): number;
export function __wbg_wasmfreewayfacility_free(a: number): void;
export function wasmfreewayfacility_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number): number;
export function wasmfreewayfacility_run_analysis(a: number, b: number): void;
export function wasmfreewayfacility_num_segments(a: number): number;
export function wasmfreewayfacility_num_periods(a: number): number;
export function wasmfreewayfacility_total_length_mi(a: number): number;
export function wasmfreewayfacility_is_oversaturated(a: number): number;
export function wasmfreewayfacility_get_speed(a: number, b: number, c: number): number;
export function wasmfreewayfacility_get_density_veh(a: number, b: number, c: number): number;
export function wasmfreewayfacility_get_density_pc(a: number, b: number, c: number): number;
export function wasmfreewayfacility_get_dc_ratio(a: number, b: number, c: number): number;
export function wasmfreewayfacility_get_queue_length_ft(a: number, b: number, c: number): number;
export function wasmfreewayfacility_get_los(a: number, b: number, c: number, d: number): void;
export function wasmfreewayfacility_get_facility_speed(a: number, b: number): number;
export function wasmfreewayfacility_get_facility_density_veh(a: number, b: number): number;
export function wasmfreewayfacility_get_facility_los(a: number, b: number, c: number): void;
export function wasmfreewayfacility_get_overall_speed(a: number): number;
export function wasmfreewayfacility_get_overall_density_veh(a: number): number;
export function wasmfreewayfacility_speed_matrix(a: number): number;
export function wasmfreewayfacility_density_matrix(a: number): number;
export function wasmfreewayfacility_dc_matrix(a: number): number;
export function wasmfreewayfacility_los_matrix(a: number): number;
export function wasmfreewayfacility_queue_matrix(a: number): number;
export function wasmfreewayfacility_results_to_js_value(a: number): number;
export function __wbg_wasmplanningfacility_free(a: number): void;
export function wasmplanningfacility_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number): number;
export function wasmplanningfacility_run_analysis(a: number, b: number): void;
export function wasmplanningfacility_num_sections(a: number): number;
export function wasmplanningfacility_total_length_mi(a: number): number;
export function wasmplanningfacility_get_dc_ratio(a: number, b: number, c: number): number;
export function wasmplanningfacility_get_section_speed(a: number, b: number, c: number): number;
export function wasmplanningfacility_get_section_density(a: number, b: number, c: number): number;
export function wasmplanningfacility_get_facility_speed(a: number, b: number): number;
export function wasmplanningfacility_get_facility_density(a: number, b: number): number;
export function wasmplanningfacility_get_facility_los(a: number, b: number, c: number): void;
export function wasmplanningfacility_results_to_js_value(a: number): number;
export function __wbg_wasmbasicfreeways_free(a: number): void;
export function wasmbasicfreeways_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number, e1: number, f1: number, g1: number, h1: number): number;
export function wasmbasicfreeways_run_operational_analysis(a: number, b: number): void;
export function wasmbasicfreeways_determine_free_flow_speed(a: number): number;
export function wasmbasicfreeways_get_ffs(a: number): number;
export function wasmbasicfreeways_get_capacity(a: number): number;
export function wasmbasicfreeways_get_adjusted_capacity(a: number): number;
export function wasmbasicfreeways_get_speed(a: number): number;
export function wasmbasicfreeways_get_density(a: number): number;
export function wasmbasicfreeways_get_vc_ratio(a: number): number;
export function wasmbasicfreeways_get_lane_count(a: number): number;
export function wasmbasicfreeways_get_e_t(a: number): number;
export function wasmbasicfreeways_results_to_js_value(a: number): number;
export function __wbg_wasmweavingsegment_free(a: number): void;
export function wasmweavingsegment_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number, e1: number, f1: number, g1: number, h1: number, i1: number, j1: number, k1: number, l1: number, m1: number, n1: number): number;
export function wasmweavingsegment_run_analysis(a: number, b: number): void;
export function wasmweavingsegment_determine_demand_flow(a: number, b: number): void;
export function wasmweavingsegment_determine_configuration_characteristics(a: number): number;
export function wasmweavingsegment_determine_max_weaving_length(a: number): number;
export function wasmweavingsegment_determine_capacity(a: number): number;
export function wasmweavingsegment_determine_lane_changing_rates(a: number): number;
export function wasmweavingsegment_estimate_speed(a: number, b: number): void;
export function wasmweavingsegment_determine_density(a: number): number;
export function wasmweavingsegment_determine_los(a: number, b: number): void;
export function wasmweavingsegment_get_flow_weaving(a: number): number;
export function wasmweavingsegment_get_flow_total(a: number): number;
export function wasmweavingsegment_get_volume_ratio(a: number): number;
export function wasmweavingsegment_get_lc_min(a: number): number;
export function wasmweavingsegment_get_l_max(a: number): number;
export function wasmweavingsegment_is_weaving(a: number): number;
export function wasmweavingsegment_get_capacity(a: number): number;
export function wasmweavingsegment_get_vc_ratio(a: number): number;
export function wasmweavingsegment_get_lc_all(a: number): number;
export function wasmweavingsegment_get_speed_weaving(a: number): number;
export function wasmweavingsegment_get_speed_nonweaving(a: number): number;
export function wasmweavingsegment_get_speed_avg(a: number): number;
export function wasmweavingsegment_get_density(a: number): number;
export function wasmweavingsegment_get_los(a: number, b: number): void;
export function wasmweavingsegment_results_to_js_value(a: number): number;
export function wasmweavingsegment_get_flow_nonweaving(a: number): number;
export function __wbg_wasmurbansegment_free(a: number): void;
export function wasmurbansegment_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number, e1: number, f1: number, g1: number, h1: number, i1: number, j1: number, k1: number, l1: number, m1: number, n1: number, o1: number, p1: number, q1: number, r1: number, s1: number, t1: number, u1: number, v1: number, w1: number, x1: number, y1: number, z1: number): number;
export function wasmurbansegment_analyze(a: number, b: number): void;
export function wasmurbansegment_get_base_ffs(a: number, b: number): void;
export function wasmurbansegment_get_free_flow_speed(a: number, b: number): void;
export function wasmurbansegment_get_running_time(a: number, b: number): void;
export function wasmurbansegment_get_running_speed(a: number, b: number): void;
export function wasmurbansegment_get_proportion_arriving_green(a: number, b: number): void;
export function wasmurbansegment_get_access_point_delay(a: number, b: number): void;
export function wasmurbansegment_get_through_delay(a: number, b: number): void;
export function wasmurbansegment_get_full_stop_rate(a: number, b: number): void;
export function wasmurbansegment_get_travel_speed(a: number, b: number): void;
export function wasmurbansegment_get_spatial_stop_rate(a: number, b: number): void;
export function wasmurbansegment_get_vc_ratio(a: number, b: number): void;
export function wasmurbansegment_get_demand_exceeds_capacity(a: number): number;
export function wasmurbansegment_get_perception_score(a: number, b: number): void;
export function wasmurbansegment_get_los(a: number, b: number): void;
export function wasmurbansegment_results_to_js_value(a: number): number;
export function __wbg_wasmsubsegment_free(a: number): void;
export function wasmsubsegment_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): number;
export function wasmsubsegment_to_js_value(a: number): number;
export function wasmsubsegment_get_length(a: number): number;
export function wasmsubsegment_get_avg_speed(a: number): number;
export function wasmsubsegment_get_hor_class(a: number): number;
export function __wbg_wasmsegment_free(a: number): void;
export function wasmsegment_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number, e1: number, f1: number, g1: number, h1: number, i1: number): number;
export function wasmsegment_to_js_value(a: number): number;
export function wasmsegment_get_passing_type(a: number): number;
export function wasmsegment_get_length(a: number): number;
export function wasmsegment_get_grade(a: number): number;
export function wasmsegment_get_spl(a: number): number;
export function wasmsegment_get_is_hc(a: number): number;
export function wasmsegment_get_volume(a: number): number;
export function wasmsegment_get_volume_op(a: number): number;
export function wasmsegment_get_flow_rate(a: number): number;
export function wasmsegment_get_flow_rate_o(a: number): number;
export function wasmsegment_get_capacity(a: number): number;
export function wasmsegment_get_ffs(a: number): number;
export function wasmsegment_get_avg_speed(a: number): number;
export function wasmsegment_get_subsegments(a: number): number;
export function wasmsegment_get_vertical_class(a: number): number;
export function wasmsegment_get_phf(a: number): number;
export function wasmsegment_get_phv(a: number): number;
export function wasmsegment_get_percent_followers(a: number): number;
export function wasmsegment_get_followers_density(a: number): number;
export function wasmsegment_get_followers_density_mid(a: number): number;
export function wasmsegment_get_hor_class(a: number): number;
export function __wbg_wasmtwolanehighways_free(a: number): void;
export function wasmtwolanehighways_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): number;
export function wasmtwolanehighways_get_segments(a: number): number;
export function wasmtwolanehighways_identify_vertical_class(a: number, b: number, c: number): void;
export function wasmtwolanehighways_determine_demand_flow(a: number, b: number, c: number): void;
export function wasmtwolanehighways_determine_vertical_alignment(a: number, b: number): number;
export function wasmtwolanehighways_determine_free_flow_speed(a: number, b: number): number;
export function wasmtwolanehighways_estimate_average_speed(a: number, b: number, c: number): void;
export function wasmtwolanehighways_estimate_percent_followers(a: number, b: number): number;
export function wasmtwolanehighways_estimate_average_speed_sf(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function wasmtwolanehighways_estimate_percent_followers_sf(a: number, b: number, c: number, d: number): number;
export function wasmtwolanehighways_determine_follower_density_pl(a: number, b: number, c: number): void;
export function wasmtwolanehighways_determine_follower_density_pc_pz(a: number, b: number): number;
export function wasmtwolanehighways_determine_adjustment_to_follower_density(a: number, b: number): number;
export function wasmtwolanehighways_determine_segment_los(a: number, b: number, c: number, d: number): number;
export function wasmtwolanehighways_determine_facility_los(a: number, b: number, c: number): number;
export function wasmsubsegment_get_design_rad(a: number): number;
export function wasmsubsegment_get_central_angle(a: number): number;
export function wasmsubsegment_get_sup_ele(a: number): number;
export function wasmsegment_subsegs_to_js_value(a: number): number;
export function wasmtwolanehighways_segs_to_js_value(a: number): number;
export function __wbg_wasmurbanreliability_free(a: number): void;
export function wasmurbanreliability_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number): number;
export function wasmurbanreliability_add_segment(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number): void;
export function wasmurbanreliability_run(a: number, b: number): void;
export function wasmurbanreliability_num_segments(a: number): number;
export function wasmurbanreliability_num_scenarios(a: number): number;
export function wasmurbanreliability_num_weather_events(a: number): number;
export function wasmurbanreliability_num_incidents(a: number): number;
export function wasmurbanreliability_get_base_free_flow_travel_time(a: number, b: number): void;
export function wasmurbanreliability_get_mean_travel_time(a: number, b: number): void;
export function wasmurbanreliability_get_total_vhd(a: number, b: number): void;
export function wasmurbanreliability_tti_mean(a: number): number;
export function wasmurbanreliability_tti_percentile(a: number, b: number): number;
export function wasmurbanreliability_reliability_rating(a: number): number;
export function wasmurbanreliability_results_to_js_value(a: number): number;
export function __wbg_wasmmanagedlanes_free(a: number): void;
export function wasmmanagedlanes_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): number;
export function wasmmanagedlanes_run_analysis(a: number, b: number): void;
export function wasmmanagedlanes_calculate_breakpoint(a: number): number;
export function wasmmanagedlanes_calculate_capacity(a: number): number;
export function wasmmanagedlanes_calculate_speed(a: number): number;
export function wasmmanagedlanes_calculate_density(a: number): number;
export function wasmmanagedlanes_determine_los(a: number, b: number): void;
export function wasmmanagedlanes_set_demand(a: number, b: number): void;
export function wasmmanagedlanes_set_gp_density(a: number, b: number): void;
export function wasmmanagedlanes_get_breakpoint(a: number): number;
export function wasmmanagedlanes_get_capacity(a: number): number;
export function wasmmanagedlanes_get_speed(a: number): number;
export function wasmmanagedlanes_get_density(a: number): number;
export function wasmmanagedlanes_get_los(a: number, b: number): void;
export function wasmmanagedlanes_has_friction_effect(a: number): number;
export function wasmmanagedlanes_is_friction_active(a: number): number;
export function wasmmanagedlanes_results_to_js_value(a: number): number;
export function __wbg_wasmrampsegment_free(a: number): void;
export function wasmrampsegment_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number, d1: number, e1: number, f1: number, g1: number, h1: number, i1: number, j1: number, k1: number, l1: number, m1: number, n1: number, o1: number, p1: number, q1: number, r1: number, s1: number, t1: number, u1: number, v1: number): number;
export function wasmrampsegment_run_analysis(a: number, b: number): void;
export function wasmrampsegment_determine_demand_flow(a: number, b: number): void;
export function wasmrampsegment_estimate_v12(a: number): number;
export function wasmrampsegment_determine_capacity(a: number): number;
export function wasmrampsegment_determine_density(a: number): number;
export function wasmrampsegment_determine_los(a: number, b: number): void;
export function wasmrampsegment_estimate_speed(a: number, b: number): void;
export function wasmrampsegment_get_flow_freeway(a: number): number;
export function wasmrampsegment_get_flow_ramp(a: number): number;
export function wasmrampsegment_get_p_f(a: number, b: number): void;
export function wasmrampsegment_get_v12(a: number): number;
export function wasmrampsegment_get_vr12(a: number): number;
export function wasmrampsegment_get_capacity_freeway(a: number): number;
export function wasmrampsegment_get_capacity_ramp(a: number): number;
export function wasmrampsegment_get_vc_ratio(a: number): number;
export function wasmrampsegment_get_demand_exceeds_capacity(a: number): number;
export function wasmrampsegment_get_exceeds_max_desirable(a: number): number;
export function wasmrampsegment_get_density(a: number): number;
export function wasmrampsegment_get_speed_ramp(a: number): number;
export function wasmrampsegment_get_speed_outer(a: number, b: number): void;
export function wasmrampsegment_get_speed_avg(a: number): number;
export function wasmrampsegment_get_los(a: number, b: number): void;
export function wasmrampsegment_results_to_js_value(a: number): number;
export function __wbg_wasmurbanfacility_free(a: number): void;
export function wasmurbanfacility_new(a: number, b: number): number;
export function wasmurbanfacility_add_segment(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number): void;
export function wasmurbanfacility_analyze(a: number, b: number): void;
export function wasmurbanfacility_num_segments(a: number): number;
export function wasmurbanfacility_get_length_ft(a: number): number;
export function wasmurbanfacility_get_base_ffs(a: number, b: number): void;
export function wasmurbanfacility_get_travel_speed(a: number, b: number): void;
export function wasmurbanfacility_get_travel_time(a: number, b: number): void;
export function wasmurbanfacility_get_base_free_flow_travel_time(a: number, b: number): void;
export function wasmurbanfacility_get_spatial_stop_rate(a: number, b: number): void;
export function wasmurbanfacility_get_critical_vc_ratio(a: number, b: number): void;
export function wasmurbanfacility_get_perception_score(a: number, b: number): void;
export function wasmurbanfacility_get_los(a: number, b: number): void;
export function wasmurbanfacility_get_poorest_segment_los(a: number, b: number): void;
export function wasmurbanfacility_segments_to_js_value(a: number): number;
export function wasmurbanfacility_results_to_js_value(a: number): number;
export function __wbg_wasmsignalizedintersection_free(a: number): void;
export function wasmsignalizedintersection_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number): number;
export function wasmsignalizedintersection_from_config(a: number, b: number): void;
export function wasmsignalizedintersection_analyze(a: number): void;
export function wasmsignalizedintersection_get_cycle_length_s(a: number): number;
export function wasmsignalizedintersection_get_intersection_delay_s(a: number, b: number): void;
export function wasmsignalizedintersection_get_intersection_los(a: number, b: number): void;
export function wasmsignalizedintersection_get_critical_vc_ratio(a: number, b: number): void;
export function wasmsignalizedintersection_approach_delay_s(a: number, b: number, c: number): number;
export function wasmsignalizedintersection_approach_los(a: number, b: number, c: number, d: number): void;
export function wasmsignalizedintersection_lane_groups_to_js_value(a: number): number;
export function wasmsignalizedintersection_results_to_js_value(a: number): number;
export function __wbg_wasmfreewayreliability_free(a: number): void;
export function wasmfreewayreliability_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number): number;
export function wasmfreewayreliability_run(a: number, b: number): void;
export function wasmfreewayreliability_num_scenarios(a: number): number;
export function wasmfreewayreliability_num_observations(a: number): number;
export function wasmfreewayreliability_free_flow_travel_time_min(a: number): number;
export function wasmfreewayreliability_expected_vhd(a: number): number;
export function wasmfreewayreliability_tti_mean(a: number): number;
export function wasmfreewayreliability_tti_percentile(a: number, b: number): number;
export function wasmfreewayreliability_misery_index(a: number): number;
export function wasmfreewayreliability_reliability_rating(a: number): number;
export function wasmfreewayreliability_semi_std_dev(a: number): number;
export function wasmfreewayreliability_failure_pct_below_speed(a: number, b: number): number;
export function wasmfreewayreliability_scenario_probabilities(a: number, b: number): void;
export function wasmfreewayreliability_scenario_tti_matrix(a: number): number;
export function wasmfreewayreliability_results_to_js_value(a: number): number;
export function __wbg_wasmroundabouts_free(a: number): void;
export function wasmroundabouts_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, a1: number, b1: number, c1: number): void;
export function wasmroundabouts_analyze(a: number): void;
export function wasmroundabouts_set_calibration(a: number, b: number, c: number): void;
export function wasmroundabouts_get_circulating_flow_pce(a: number, b: number, c: number, d: number): void;
export function wasmroundabouts_get_lane_count(a: number, b: number, c: number, d: number): void;
export function wasmroundabouts_lane_result_to_js_value(a: number, b: number, c: number, d: number, e: number): void;
export function wasmroundabouts_bypass_result_to_js_value(a: number, b: number, c: number, d: number): void;
export function wasmroundabouts_get_approach_delay(a: number, b: number, c: number, d: number): void;
export function wasmroundabouts_get_approach_los(a: number, b: number, c: number, d: number): void;
export function wasmroundabouts_get_intersection_delay(a: number, b: number): void;
export function wasmroundabouts_get_intersection_los(a: number, b: number): void;
export function wasmroundabouts_results_to_js_value(a: number): number;
export function __wbg_wasmawsc_free(a: number): void;
export function wasmawsc_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number): void;
export function wasmawsc_analyze(a: number): void;
export function wasmawsc_get_iterations(a: number, b: number): void;
export function wasmawsc_get_lane_count(a: number, b: number, c: number, d: number): void;
export function wasmawsc_get_departure_headway(a: number, b: number, c: number, d: number, e: number): void;
export function wasmawsc_get_degree_of_utilization(a: number, b: number, c: number, d: number, e: number): void;
export function wasmawsc_get_service_time(a: number, b: number, c: number, d: number, e: number): void;
export function wasmawsc_get_lane_delay(a: number, b: number, c: number, d: number, e: number): void;
export function wasmawsc_get_lane_los(a: number, b: number, c: number, d: number, e: number): void;
export function wasmawsc_get_lane_queue_95(a: number, b: number, c: number, d: number, e: number): void;
export function wasmawsc_compute_lane_capacity(a: number, b: number, c: number, d: number, e: number): void;
export function wasmawsc_get_approach_delay(a: number, b: number, c: number, d: number): void;
export function wasmawsc_get_approach_los(a: number, b: number, c: number, d: number): void;
export function wasmawsc_get_intersection_delay(a: number, b: number): void;
export function wasmawsc_get_intersection_los(a: number, b: number): void;
export function wasmawsc_results_to_js_value(a: number): number;
export function __wbg_wasminterchange_free(a: number): void;
export function wasminterchange_new(a: number, b: number): void;
export function wasminterchange_analyze(a: number): void;
export function wasminterchange_get_cycle_length_s(a: number): number;
export function wasminterchange_get_peak_hour_factor(a: number): number;
export function wasminterchange_get_interchange_ett_s(a: number, b: number): void;
export function wasminterchange_get_interchange_los(a: number, b: number): void;
export function wasminterchange_od_results_to_js_value(a: number): number;
export function wasminterchange_lane_group_results_to_js_value(a: number): number;
export function __wbg_wasmdisplacedleftturn_free(a: number): void;
export function wasmdisplacedleftturn_new(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function wasmdisplacedleftturn_get_intersection_ett_s(a: number): number;
export function wasmdisplacedleftturn_get_los(a: number, b: number): void;
export function __wbg_wasmexclusivepedestrianfacility_free(a: number): void;
export function wasmexclusivepedestrianfacility_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number): number;
export function wasmexclusivepedestrianfacility_analyze(a: number, b: number): void;
export function wasmexclusivepedestrianfacility_get_effective_width(a: number): number;
export function wasmexclusivepedestrianfacility_get_flow_rate_15min(a: number): number;
export function wasmexclusivepedestrianfacility_get_unit_flow_rate(a: number): number;
export function wasmexclusivepedestrianfacility_get_pedestrian_space(a: number): number;
export function wasmexclusivepedestrianfacility_get_vc_ratio(a: number): number;
export function wasmexclusivepedestrianfacility_results_to_js_value(a: number): number;
export function __wbg_wasmsharedusepathpedestrian_free(a: number): void;
export function wasmsharedusepathpedestrian_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number): number;
export function wasmsharedusepathpedestrian_analyze(a: number, b: number): void;
export function wasmsharedusepathpedestrian_get_meeting_events(a: number): number;
export function wasmsharedusepathpedestrian_results_to_js_value(a: number): number;
export function __wbg_wasmoffstreetbicyclefacility_free(a: number): void;
export function wasmoffstreetbicyclefacility_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number): number;
export function wasmoffstreetbicyclefacility_analyze(a: number, b: number): void;
export function wasmoffstreetbicyclefacility_get_active_passings_per_minute(a: number): number;
export function wasmoffstreetbicyclefacility_get_meetings_per_minute(a: number): number;
export function wasmoffstreetbicyclefacility_get_effective_lanes(a: number): number;
export function wasmoffstreetbicyclefacility_get_probability_delayed_passing(a: number): number;
export function wasmoffstreetbicyclefacility_get_delayed_passings_per_minute(a: number): number;
export function wasmoffstreetbicyclefacility_get_weighted_events_per_minute(a: number): number;
export function wasmoffstreetbicyclefacility_get_blos_score(a: number): number;
export function wasmoffstreetbicyclefacility_results_to_js_value(a: number): number;
export function wasmsharedusepathpedestrian_get_passing_events(a: number): number;
export function wasmsharedusepathpedestrian_get_total_events(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
