[package]
name = "HCM-middleware"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.87"
traffic-sim = "0.1.1"
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3.64"
crosstraffic_middleware = "0.1.0"