name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout
      - name: Use Node.js
        uses: actions/setup-node
        with:
          node-version: 17.x
      - name: run CI
        run: |
          npm ci
          npm run build --if-present
          npm test