name: Format

on: push

jobs:
  format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: npm install
        run: |
          npm install
      - name: format code
        run: |
          npm run format
      - name: push formatted code
        uses: actions/checkout@v4
        env:
          SECRET_TOKEN: ${{ secrets.CREDENTIALS_TOKEN }}
          SECRET_REPO: ${{ secrets.CREDENTIALS_REPO }}
        with:
          repository: crosstraffic/${{ secrets.CREDENTIALS_REPO }}
          token: ${{ secrets.CREDENTIALS_TOKEN }}
          path: ${{ secrets.CREDENTIALS_REPO}}