name: Format

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: npm install
        run: |
          npm install
      - name: format code
        run: |
          npm run format
      - name: push formatted code
        run: |
          git config --global user.name raynbowy23
          git config --global user.email lov.us.basketball@gmail.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add --all
          git diff-index --quiet HEAD || git commit -m "Format Code"
          git pull
          git push