name: Format

on: push

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.x
      - name: npm install
        run: |
          npm install
      - name: format code
        run: |
          npm run format
      - name: push formatted code
        uses: actions/checkout@v3
        env:
          SECRET_TOKEN: ${{ secrets.CREDENTIALS_TOKEN }}
          SECRET_REPO: ${{ secrets.CREDENTIALS_REPO }}
        with:
          repository: raynbowy23/${{ secrets.CREDENTIALS_REPO }}
          token: ${{ secrets.CREDENTIALS_TOKEN }}
          path: ${{ secrets.CREDENTIALS_REPO}}