name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      - name: Build Vite app
        run: npm run build
      
      - name: Start Vite preview server
        run: npm run preview &
      
      - name: Run Playwright tests
        run: |
          if ls tests/*.spec.ts 1> /dev/null 2>&1; then
            npx playwright test --reporter=html
          else
            echo "No Playwright test files found. Skipping test step."
          fi

      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        continue-on-error: true
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
